@unstable(feature = tls)
interface tls {
    @unstable(feature = tls)
    use wasi:io/streams@0.2.0.{input-stream, output-stream};
    @unstable(feature = tls)
    use wasi:io/poll@0.2.0.{pollable};

    @unstable(feature = tls)
    resource client-connection {
        @unstable(feature = tls)
        constructor(input: input-stream, output: output-stream);
        @unstable(feature = tls)
        connect: func(server-name: string) -> result<client-handshake>;
    }

    @unstable(feature = tls)
    resource client-handshake {
        @unstable(feature = tls)
        finish: static func(this: client-handshake) -> future-streams;
    }

    @unstable(feature = tls)
    resource future-streams {
        @unstable(feature = tls)
        subscribe: func() -> pollable;
        @unstable(feature = tls)
        get: func() -> option<result<result<tuple<input-stream, output-stream>>>>;
    }

    // TODO: this belongs in `wasi:io/streams` but we put it here temporarily to
    // make implementation easier (i.e. avoid forking `wasmtime_wasi`).
    @unstable(feature = tls)
    make-pipe: func() -> tuple<input-stream, output-stream>;
}

